<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "news".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $date
 * @property string $photo
 */
class News extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }


    public $photoFile;

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'description'], 'required'],
            [['date'], 'integer'],
            [['name'], 'string', 'max' => 30],
            [['description'], 'string', 'max' => 2000],
            [['photo'], 'string', 'max' => 255],
            [['photoFile'], 'file', 'extensions' => 'png, jpeg, jpg'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'description' => 'Описание',
            'date' => 'Date',
            'photo' => 'Photo',
            'dateText' => 'Дата',
            'photoFile' => 'Фотография'
        ];
    }

    public function init()
    {
        if ($this->isNewRecord)
            $this->date = time();

        parent::init();
    }

    public function getDateText()
    {
        return date("d.m.Y H:i:s", $this->date);
    }

    public function setDateText($value)
    {
        $this->date = strtotime($value);
    }

    public function savePhoto()
    {
        if ($this->photoFile) {
            $dir = 'uploads/';

            if (!is_dir($dir))
                mkdir($dir);

            $dir .= time().trim($this->photoFile->baseName) . '.' . $this->photoFile->extension;
            $this->photoFile->saveAs($dir);

            if ($this->photo && is_file($this->photo))
                unlink($this->photo);

            $this->photo = $dir;

            return true;
        }

        return false;
    }

    public function beforeDelete()
    {
        if (is_file($this->photo))
            unlink($this->photo);

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
